### ISSUE TITLE
Does not work with IDA 7.2

### ISSUE THREAD

**Issue by Lissanro** [scottmudge/DebugAutoPatch#1]
I tried it, but if I restart debug session, patches do not persist. If I create a patch while not debugging and then start debug, the patch is not automatically applied. I tried clicking "Enable Auto-Patching" before creating a patch and after, it has no effect. I also tried newer devel version, and it has the same issues. I tried to click "Apply Patches to Current Process" but then I get the following error:
```
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.2/plugins/DebugAutoPatch.py", line 604, in activate
    self.plugin.apply_patches_to_current_proc()
AttributeError: 'DebugAutoPatchPlugin' object has no attribute 'apply_patches_to_current_proc'
```
If I'm doing something wrong, please let me know. So far I couldn't get working neither automatic nor manual patching to current process.
